### ISSUE TITLE
include 'ocurrenceStatus' and 'coordinateUncertaintyInMeters'

### ISSUE THREAD

**Issue by AMBarbosa** [ropensci/occCite#22]
Hi,
At least two of GBIF's columns should be added to the `occCite::occQuery()` output, as they are crucial for cleaning the occurrence data: 'ocurrenceStatus' (which can be "Present" or "Absent"!) and 'coordinateUncertaintyInMeters' (as many observations are very far away from their assigned point coordinates, which can be e.g. continent centroids). If the same (or equivalent) columns are not available in BIEN, these columns could get NA values in those rows.
Cheers!

**Comment by hannahlowens** [comment]
Thanks for the suggestions, and for submitting them as an issue!

First, I forgot when we had our email exchange that I had already set things up so that GBIF searches in occCite are limited to only return records with occurrenceStatus == "PRESENT". This is documented in `getGBIFpoints()`, but I have added this data to the documentation for `occQuery()` to make it even clearer.

Second, I have added coordinateUncertaintyInMeters as a column in the occurrence results table.

Thanks again!
